### ISSUE TITLE
Likely missing another check for bytes in clean_env_string

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/vcrpy-cleaner#20]
## Context

In our TDX SOAR app, we still get a 'bytes' error from running `clean_env_strings` on one of our API responses.
In these cases, we want `clean_env_strings` to notice the `bytes` type of the content, and exit and do nothing, rather than raise an error.

Most likely we have found another corner case for building a response body that results in `clean_env_strings` trying to process `bytes`.

https://github.com/techservicesillinois/secops-soar-tdx/issues/39#issuecomment-1591980138

**Comment by edthedev** [comment]
This is likely blocking https://github.com/techservicesillinois/secops-soar-tdx/issues/39

**Comment by tzturner** [comment]
Something like this?

https://github.com/techservicesillinois/vcrpy-cleaner/blob/0207f131960002cfaff09373d105a38f522cd41e/src/vcr_cleaner/cleaners/env_strings.py#L16-L19

**Comment by edthedev** [comment]
> Something like this?
> 
> https://github.com/techservicesillinois/vcrpy-cleaner/blob/0207f131960002cfaff09373d105a38f522cd41e/src/vcr_cleaner/cleaners/env_strings.py#L16-L19

Pretty much exactly like that. I'm really not sure why we're still seeing that error.
It's probably another side-effect of the fact that our first use case was a dictionary with a key named 'string', and this use case is just a string type body.

**Comment by edthedev** [comment]
Oh hey, I called this use case 'Nobody is going to do that' in a previous commit.

```
 {'body': {'string': b'\x1f\x8
```
