### ISSUE TITLE
Submit before_record_interaction to VCRpy to replace CleanYAMLSerializer

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/vcrpy-cleaner#4]
Discussing with @ddriddle: 

The CleanYAMLSerializer code is a work around for `before_record_response` to allow us to access the request to match the URI. Should we consider contributing code to VCRpy that adds access to the request to the `before_record_response` param?

Another approach might be to add something like `before_record_interaction` that would give access to the response and the request.

**Comment by zdc217** [comment]
Per team discussion, Ed approves and we should do this

Similar issues have been submitted. We could potentially close those out by contributing this code to VCRpy

https://github.com/kevin1024/vcrpy/issues/556
https://github.com/kevin1024/vcrpy/issues/527

**Comment by tzturner** [comment]
Pull request put in here!
https://github.com/kevin1024/vcrpy/pull/679
