### ISSUE TITLE
Remove CleanYAMLSerializer

### ISSUE THREAD

**Issue by tzturner** [techservicesillinois/vcrpy-cleaner#5]
Once the following PR has been merged, remove `CleanYAMLSerializer` and update code and docs.

https://github.com/kevin1024/vcrpy/pull/679

**Comment by edthedev** [comment]
Considering that https://github.com/kevin1024/vcrpy/pull/679 shows no sign of being merged, and related issues and features are still in heavy flux, I'm now inclined that we probably want to continue to use a serializer as our entry point for the foreseeable future.

**Comment by edthedev** [comment]
Closing this as 'not planned' for now. Can revisit later.
