### ISSUE TITLE
Add mypy support

### ISSUE THREAD

**Issue by mpitcel** [techservicesillinois/vcrpy-cleaner#9]
Clients importing this library fail `mypy` tests due to missing type hints. 

See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports for details. 

Discovered while working on: https://github.com/techservicesillinois/splunk-soar-template/issues/12

**Comment by zdc217** [comment]
Looking at https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages for guidance on adding mypy type hints
